# Codespaces-specific configuration
# Activated automatically when CODESPACES=true environment variable is detected

spring:
  # Override: Use local Ollama instead of Groq
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.1:8b
          temperature: 0.1
          # No max-tokens for Ollama needed

# Logging for demo
logging:
  level:
    com.agenticfraud: INFO
    org.springframework.ai: DEBUG